### ISSUE TITLE
Personal data

### ISSUE THREAD

**Issue by RealKolago** [xriss/dataiati#1]
Hello Kriss,

this file (https://github.com/xriss/dataiati/blob/main/xml/ifcwbg-9/xm-dac-903-spi-29923.xml) contains personal data of employees of Commerzbank AG. Please delete this file or remove the PII of our employees.

Please also delete the file history.
  
Thank you for your cooperation.
 
Kind regards
 
Andrej Meuer
 
Commerzbank AG
Group Technology Foundations
Security Threat Intelligence

**Comment by xriss** [comment]
This repo contains published IATI data that has been cleaned up and re formatted in preparation for use in other tools. This is done daily and automatically.

As such manually deleting it here will not help, it will be automatically added again as it is still part of the IATI Data.

In this case the data originates within this IATI dataset published upon the IATI registry.

https://iatiregistry.org/dataset/ifcwbg-9

which describes this XML file

https://disclosures.ifc.org/IATI/IFC-9.xml

Any attempts to delete this information *must* start with the IATI registry or it will not stay deleted, it will remain available here and in many other tools and databases across the internet as it is published as Open Data ( https://opendefinition.org/od/2.1/en/ )

**Comment by RealKolago** [comment]
Thank you for the clarification, in this context the deletion of the data does indeed not seem to be effective. Thank you for the quick response and cooperation! The incident can be closed.
